package ru.romanow.state.machine.models.vssdv;

public enum VssdvStates {
    CALCULATION_STARTED,

    VAR_DATA_PREPARED,
    VAR_DATA_COPIED_TO_STAGED,

    // ETL
    VAR_ETL_START,
    VAR_ETL_SEND_TO_DRP,
    VAR_ETL_ACCEPTED,
    VAR_ETL_COMPLETED,

    // Calculation
    VAR_CALCULATION_START,
    VAR_CALCULATION_SENT_TO_DRP,
    VAR_CALCULATION_ACCEPTED,
    VAR_CALCULATION_COMPLETED,

    // Reverse ETL
    VAR_REVERSED_ETL_START,
    VAR_REVERSED_ETL_SENT_TO_DRP,
    VAR_REVERSED_ETL_ACCEPTED,
    VAR_REVERSED_COMPLETED,

    VAR_DATA_COPIED_FROM_STAGED,

    VAR_CALCULATION_FINISHED,

    BLACK_MODEL_DATA_PREPARED,
    BLACK_MODEL_DATA_COPIED_TO_STAGED,

    // ETL
    BLACK_MODEL_ETL_START,
    BLACK_MODEL_ETL_SEND_TO_DRP,
    BLACK_MODEL_ETL_ACCEPTED,
    BLACK_MODEL_ETL_COMPLETED,

    // Calculation
    BLACK_MODEL_CALCULATION_START,
    BLACK_MODEL_CALCULATION_SENT_TO_DRP,
    BLACK_MODEL_CALCULATION_ACCEPTED,
    BLACK_MODEL_CALCULATION_COMPLETED,

    // Reverse ETL
    BLACK_MODEL_REVERSED_ETL_START,
    BLACK_MODEL_REVERSED_ETL_SENT_TO_DRP,
    BLACK_MODEL_REVERSED_ETL_ACCEPTED,
    BLACK_MODEL_REVERSED_COMPLETED,

    BLACK_MODEL_DATA_COPIED_FROM_STAGED,

    BLACK_MODEL_CALCULATION_FINISHED,

    VSSDV_DATA_PREPARED,
    VSSDV_DATA_COPIED_TO_STAGED,

    // ETL
    VSSDV_ETL_START,
    VSSDV_ETL_SEND_TO_DRP,
    VSSDV_ETL_ACCEPTED,
    VSSDV_ETL_COMPLETED,

    // Calculation
    VSSDV_CALCULATION_START,
    VSSDV_CALCULATION_SENT_TO_DRP,
    VSSDV_CALCULATION_ACCEPTED,
    VSSDV_CALCULATION_COMPLETED,

    // Reverse ETL
    VSSDV_REVERSED_ETL_START,
    VSSDV_REVERSED_ETL_SENT_TO_DRP,
    VSSDV_REVERSED_ETL_ACCEPTED,
    VSSDV_REVERSED_COMPLETED,

    VSSDV_DATA_COPIED_FROM_STAGED,

    VSSDV_CALCULATION_FINISHED,

    CALCULATION_ERROR          // Расчет завершился с ошибкой
}
