package ru.romanow.state.machine.models.vssdv;

public enum VssdvEvents {
    // region Var Model
    // #################################
    // ########### VaR Model ###########
    // #################################
    VAR_MODEL_DATA_PREPARED_EVENT,               // CALCULATION_STARTED (init)             ->   VAR_MODEL_DATA_PREPARED

    VAR_MODEL_DATA_COPIED_TO_STAGED_EVENT,       // VAR_MODEL_DATA_PREPARED_EVENT          ->   VAR_MODEL_DATA_COPIED_TO_STAGED

    VAR_MODEL_ETL_START_EVENT,                   // VAR_MODEL_DATA_COPIED_TO_STAGED        ->   VAR_MODEL_ETL_START
    VAR_MODEL_ETL_SENT_TO_DRP_EVENT,             // VAR_MODEL_ETL_START                    ->   VAR_MODEL_ETL_SENT_TO_DRP
    VAR_MODEL_ETL_ACCEPTED_EVENT,                // VAR_MODEL_ETL_SENT_TO_DRP              ->   VAR_MODEL_ETL_ACCEPTED
    VAR_MODEL_ETL_COMPLETED_EVENT,               // VAR_MODEL_ETL_ACCEPTED                 ->   VAR_MODEL_ETL_COMPLETED

    VAR_MODEL_CALCULATION_START_EVENT,           // VAR_MODEL_ETL_COMPLETED                ->   VAR_MODEL_CALCULATION_START
    VAR_MODEL_CALCULATION_SENT_TO_DRP_EVENT,     // VAR_MODEL_CALCULATION_START            ->   VAR_MODEL_CALCULATION_SENT_TO_DRP
    VAR_MODEL_CALCULATION_ACCEPTED_EVENT,        // VAR_MODEL_CALCULATION_SENT_TO_DRP      ->   VAR_MODEL_CALCULATION_ACCEPTED
    VAR_MODEL_CALCULATION_COMPLETED_EVENT,       // VAR_MODEL_CALCULATION_ACCEPTED         ->   VAR_MODEL_CALCULATION_COMPLETED

    VAR_MODEL_REVERSED_ETL_START_EVENT,          // VAR_MODEL_CALCULATION_COMPLETED        ->   VAR_MODEL_REVERSED_ETL_START
    VAR_MODEL_REVERSED_ETL_SENT_TO_DRP_EVENT,    // VAR_MODEL_REVERSED_ETL_START           ->   VAR_MODEL_REVERSED_ETL_SENT_TO_DRP
    VAR_MODEL_REVERSED_ETL_ACCEPTED_EVENT,       // VAR_MODEL_REVERSED_ETL_SENT_TO_DRP     ->   VAR_MODEL_REVERSED_ETL_ACCEPTED
    VAR_MODEL_REVERSED_ETL_COMPLETED_EVENT,      // VAR_MODEL_REVERSED_ETL_ACCEPTED        ->   VAR_MODEL_REVERSED_ETL_COMPLETED

    VAR_MODEL_DATA_COPIED_FROM_STAGED_EVENT,      // VAR_MODEL_REVERSED_ETL_COMPLETED      ->   VAR_MODEL_DATA_COPIED_FROM_STAGED

    VAR_MODEL_CALCULATION_FINISHED_EVENT,         // VAR_MODEL_DATA_COPIED_FROM_STAGED     ->   VAR_MODEL_CALCULATION_FINISHED
    // endregion

    // region Black Model
    // #################################
    // ########## Black Model ##########
    // #################################
    BLACK_MODEL_DATA_PREPARED_EVENT,              // CALCULATION_STARTED (init)             ->   BLACK_MODEL_DATA_PREPARED

    BLACK_MODEL_DATA_COPIED_TO_STAGED_EVENT,      // BLACK_MODEL_DATA_PREPARED_EVENT        ->   BLACK_MODEL_DATA_COPIED_TO_STAGED

    BLACK_MODEL_ETL_START_EVENT,                  // BLACK_MODEL_DATA_COPIED_TO_STAGED      ->   BLACK_MODEL_ETL_START
    BLACK_MODEL_ETL_SENT_TO_DRP_EVENT,            // BLACK_MODEL_ETL_START                  ->   BLACK_MODEL_ETL_SENT_TO_DRP
    BLACK_MODEL_ETL_ACCEPTED_EVENT,               // BLACK_MODEL_ETL_SENT_TO_DRP            ->   BLACK_MODEL_ETL_ACCEPTED
    BLACK_MODEL_ETL_COMPLETED_EVENT,              // BLACK_MODEL_ETL_ACCEPTED               ->   BLACK_MODEL_ETL_COMPLETED

    BLACK_MODEL_CALCULATION_START_EVENT,          // BLACK_MODEL_ETL_COMPLETED              ->   BLACK_MODEL_CALCULATION_START
    BLACK_MODEL_CALCULATION_SENT_TO_DRP_EVENT,    // BLACK_MODEL_CALCULATION_START          ->   BLACK_MODEL_CALCULATION_SENT_TO_DRP
    BLACK_MODEL_CALCULATION_ACCEPTED_EVENT,       // BLACK_MODEL_CALCULATION_SENT_TO_DRP    ->   BLACK_MODEL_CALCULATION_ACCEPTED
    BLACK_MODEL_CALCULATION_COMPLETED_EVENT,      // BLACK_MODEL_CALCULATION_ACCEPTED       ->   BLACK_MODEL_CALCULATION_COMPLETED

    BLACK_MODEL_REVERSED_ETL_START_EVENT,         // BLACK_MODEL_CALCULATION_COMPLETED      ->   BLACK_MODEL_REVERSED_ETL_START
    BLACK_MODEL_REVERSED_ETL_SENT_TO_DRP_EVENT,   // BLACK_MODEL_REVERSED_ETL_START         ->   BLACK_MODEL_REVERSED_ETL_SENT_TO_DRP
    BLACK_MODEL_REVERSED_ETL_ACCEPTED_EVENT,      // BLACK_MODEL_REVERSED_ETL_SENT_TO_DRP   ->   BLACK_MODEL_REVERSED_ETL_ACCEPTED
    BLACK_MODEL_REVERSED_ETL_COMPLETED_EVENT,     // BLACK_MODEL_REVERSED_ETL_ACCEPTED      ->   BLACK_MODEL_REVERSED_ETL_COMPLETED

    BLACK_MODEL_DATA_COPIED_FROM_STAGED_EVENT,    // BLACK_MODEL_REVERSED_ETL_COMPLETED     ->   BLACK_MODEL_DATA_COPIED_FROM_STAGED

    BLACK_MODEL_CALCULATION_FINISHED_EVENT,       // BLACK_MODEL_DATA_COPIED_FROM_STAGED    ->   BLACK_MODEL_CALCULATION_FINISHED
    // endregion

    // region VSSDV
    // #################################
    // ############ VSSDV ##############
    // #################################
    VSSDV_DATA_PREPARED_EVENT,              // VAR & BLACK MODELS CALCULATION_FINISHED      ->   VSSDV_DATA_PREPARED

    VSSDV_DATA_COPIED_TO_STAGED_EVENT,      // VSSDV_DATA_PREPARED_EVENT                    ->   VSSDV_DATA_COPIED_TO_STAGED

    VSSDV_ETL_START_EVENT,                  // VSSDV_DATA_COPIED_TO_STAGED                  ->   VSSDV_ETL_START
    VSSDV_ETL_SENT_TO_DRP_EVENT,            // VSSDV_ETL_START                              ->   VSSDV_ETL_SENT_TO_DRP
    VSSDV_ETL_ACCEPTED_EVENT,               // VSSDV_ETL_SENT_TO_DRP                        ->   VSSDV_ETL_ACCEPTED
    VSSDV_ETL_COMPLETED_EVENT,              // VSSDV_ETL_ACCEPTED                           ->   VSSDV_ETL_COMPLETED

    VSSDV_CALCULATION_START_EVENT,          // VSSDV_ETL_COMPLETED                          ->   VSSDV_CALCULATION_START
    VSSDV_CALCULATION_SENT_TO_DRP_EVENT,    // VSSDV_CALCULATION_START                      ->   VSSDV_CALCULATION_SENT_TO_DRP
    VSSDV_CALCULATION_ACCEPTED_EVENT,       // VSSDV_CALCULATION_SENT_TO_DRP                ->   VSSDV_CALCULATION_ACCEPTED
    VSSDV_CALCULATION_COMPLETED_EVENT,      // VSSDV_CALCULATION_ACCEPTED                   ->   VSSDV_CALCULATION_COMPLETED

    VSSDV_REVERSED_ETL_START_EVENT,         // VSSDV_CALCULATION_COMPLETED                  ->   VSSDV_REVERSED_ETL_START
    VSSDV_REVERSED_ETL_SENT_TO_DRP_EVENT,   // VSSDV_REVERSED_ETL_START                     ->   VSSDV_REVERSED_ETL_SENT_TO_DRP
    VSSDV_REVERSED_ETL_ACCEPTED_EVENT,      // VSSDV_REVERSED_ETL_SENT_TO_DRP               ->   VSSDV_REVERSED_ETL_ACCEPTED
    VSSDV_REVERSED_ETL_COMPLETED_EVENT,         // VSSDV_REVERSED_ETL_ACCEPTED              ->   VSSDV_REVERSED_ETL_COMPLETED

    VSSDV_DATA_COPIED_FROM_STAGED_EVENT,    // VSSDV_REVERSED_ETL_COMPLETED                 ->   VSSDV_DATA_COPIED_FROM_STAGED
    VSSDV_CALCULATION_FINISHED_EVENT,       // VSSDV_DATA_COPIED_FROM_STAGED                ->   VSSDV_CALCULATION_FINISHED (end)
    // endregion

    CALCULATION_ERROR_EVENT                 // Every State                                  ->   CALCULATION_ERROR (end)
}
