package ru.romanow.state.machine.models;

public enum Events {
    CASH_FLOW_DATA_PREPARED_EVENT,              // CASH_FLOW_CALCULATION_STARTED (init) ->   CASH_FLOW_DATA_PREPARED_EVENT

    CASH_FLOW_ETL_START_EVENT,                  // CASH_FLOW_DATA_PREPARED              ->   CASH_FLOW_ETL_START
    CASH_FLOW_ETL_SENT_TO_DRP_EVENT,            // CASH_FLOW_ETL_START                  ->   CASH_FLOW_ETL_SENT_TO_DRP
    CASH_FLOW_ETL_ACCEPTED_EVENT,               // CASH_FLOW_ETL_SENT_TO_DRP            ->   CASH_FLOW_ETL_ACCEPTED
    CASH_FLOW_ETL_COMPLETED_EVENT,              // CASH_FLOW_ETL_ACCEPTED               ->   CASH_FLOW_ETL_COMPLETED

    CASH_FLOW_CALCULATION_START_EVENT,          // CASH_FLOW_ETL_COMPLETED              ->   CASH_FLOW_CALCULATION_START
    CASH_FLOW_CALCULATION_SENT_TO_DRP_EVENT,    // CASH_FLOW_CALCULATION_START          ->   CASH_FLOW_CALCULATION_SENT_TO_DRP
    CASH_FLOW_CALCULATION_ACCEPTED_EVENT,       // CASH_FLOW_CALCULATION_SENT_TO_DRP    ->   CASH_FLOW_CALCULATION_ACCEPTED
    CASH_FLOW_CALCULATION_COMPLETED_EVENT,      // CASH_FLOW_CALCULATION_ACCEPTED       ->   CASH_FLOW_CALCULATION_COMPLETED

    CASH_FLOW_REVERSED_ETL_START_EVENT,         // CASH_FLOW_CALCULATION_COMPLETED      ->   CASH_FLOW_REVERSED_ETL_START
    CASH_FLOW_REVERSED_ETL_SENT_TO_DRP_EVENT,   // CASH_FLOW_REVERSED_ETL_START         ->   CASH_FLOW_REVERSED_ETL_SENT_TO_DRP
    CASH_FLOW_REVERSED_ETL_ACCEPTED_EVENT,      // CASH_FLOW_REVERSED_ETL_SENT_TO_DRP   ->   CASH_FLOW_REVERSED_ETL_ACCEPTED
    CASH_FLOW_REVERSED_COMPLETED_EVENT,         // CASH_FLOW_REVERSED_ETL_ACCEPTED      ->   CASH_FLOW_REVERSED_COMPLETED

    CASH_FLOW_CALCULATION_FINISHED_EVENT        // CASH_FLOW_REVERSED_COMPLETED         ->   CASH_FLOW_CALCULATION_FINISHED (end)
}
